#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFacturacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_dentista")]
	public partial class DFacturacionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertfactura_odontoweb(factura_odontoweb instance);
    partial void Updatefactura_odontoweb(factura_odontoweb instance);
    partial void Deletefactura_odontoweb(factura_odontoweb instance);
    partial void InsertDosificacion(Dosificacion instance);
    partial void UpdateDosificacion(Dosificacion instance);
    partial void DeleteDosificacion(Dosificacion instance);
    partial void InsertParametroSistemas(ParametroSistemas instance);
    partial void UpdateParametroSistemas(ParametroSistemas instance);
    partial void DeleteParametroSistemas(ParametroSistemas instance);
    #endregion
		
		public DFacturacionLinqDataContext() : 
				base(global::DFacturacion.Properties.Settings.Default.db_dentistaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DFacturacionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DFacturacionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DFacturacionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DFacturacionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<factura_odontoweb> factura_odontoweb
		{
			get
			{
				return this.GetTable<factura_odontoweb>();
			}
		}
		
		public System.Data.Linq.Table<Dosificacion> Dosificacion
		{
			get
			{
				return this.GetTable<Dosificacion>();
			}
		}
		
		public System.Data.Linq.Table<ParametroSistemas> ParametroSistemas
		{
			get
			{
				return this.GetTable<ParametroSistemas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.factura_odontoweb")]
	public partial class factura_odontoweb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nit_dacasys;
		
		private int _nro_factura;
		
		private string _nro_autorizacion;
		
		private System.DateTime _fecha_emision;
		
		private string _nombre_cliente;
		
		private string _nit_cliente;
		
		private string _codigo_control;
		
		private System.DateTime _fecha_limite;
		
		private int _detalle_cantidad;
		
		private double _precio_unitario;
		
		private double _total;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNit_dacasysChanging(string value);
    partial void OnNit_dacasysChanged();
    partial void Onnro_facturaChanging(int value);
    partial void Onnro_facturaChanged();
    partial void Onnro_autorizacionChanging(string value);
    partial void Onnro_autorizacionChanged();
    partial void Onfecha_emisionChanging(System.DateTime value);
    partial void Onfecha_emisionChanged();
    partial void Onnombre_clienteChanging(string value);
    partial void Onnombre_clienteChanged();
    partial void Onnit_clienteChanging(string value);
    partial void Onnit_clienteChanged();
    partial void Oncodigo_controlChanging(string value);
    partial void Oncodigo_controlChanged();
    partial void Onfecha_limiteChanging(System.DateTime value);
    partial void Onfecha_limiteChanged();
    partial void Ondetalle_cantidadChanging(int value);
    partial void Ondetalle_cantidadChanged();
    partial void Onprecio_unitarioChanging(double value);
    partial void Onprecio_unitarioChanged();
    partial void OntotalChanging(double value);
    partial void OntotalChanged();
    #endregion
		
		public factura_odontoweb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nit_dacasys", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Nit_dacasys
		{
			get
			{
				return this._Nit_dacasys;
			}
			set
			{
				if ((this._Nit_dacasys != value))
				{
					this.OnNit_dacasysChanging(value);
					this.SendPropertyChanging();
					this._Nit_dacasys = value;
					this.SendPropertyChanged("Nit_dacasys");
					this.OnNit_dacasysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_factura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nro_factura
		{
			get
			{
				return this._nro_factura;
			}
			set
			{
				if ((this._nro_factura != value))
				{
					this.Onnro_facturaChanging(value);
					this.SendPropertyChanging();
					this._nro_factura = value;
					this.SendPropertyChanged("nro_factura");
					this.Onnro_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_autorizacion", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nro_autorizacion
		{
			get
			{
				return this._nro_autorizacion;
			}
			set
			{
				if ((this._nro_autorizacion != value))
				{
					this.Onnro_autorizacionChanging(value);
					this.SendPropertyChanging();
					this._nro_autorizacion = value;
					this.SendPropertyChanged("nro_autorizacion");
					this.Onnro_autorizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_emision", DbType="Date NOT NULL")]
		public System.DateTime fecha_emision
		{
			get
			{
				return this._fecha_emision;
			}
			set
			{
				if ((this._fecha_emision != value))
				{
					this.Onfecha_emisionChanging(value);
					this.SendPropertyChanging();
					this._fecha_emision = value;
					this.SendPropertyChanged("fecha_emision");
					this.Onfecha_emisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cliente", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre_cliente
		{
			get
			{
				return this._nombre_cliente;
			}
			set
			{
				if ((this._nombre_cliente != value))
				{
					this.Onnombre_clienteChanging(value);
					this.SendPropertyChanging();
					this._nombre_cliente = value;
					this.SendPropertyChanged("nombre_cliente");
					this.Onnombre_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_cliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string nit_cliente
		{
			get
			{
				return this._nit_cliente;
			}
			set
			{
				if ((this._nit_cliente != value))
				{
					this.Onnit_clienteChanging(value);
					this.SendPropertyChanging();
					this._nit_cliente = value;
					this.SendPropertyChanged("nit_cliente");
					this.Onnit_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_control", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string codigo_control
		{
			get
			{
				return this._codigo_control;
			}
			set
			{
				if ((this._codigo_control != value))
				{
					this.Oncodigo_controlChanging(value);
					this.SendPropertyChanging();
					this._codigo_control = value;
					this.SendPropertyChanged("codigo_control");
					this.Oncodigo_controlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_limite", DbType="Date NOT NULL")]
		public System.DateTime fecha_limite
		{
			get
			{
				return this._fecha_limite;
			}
			set
			{
				if ((this._fecha_limite != value))
				{
					this.Onfecha_limiteChanging(value);
					this.SendPropertyChanging();
					this._fecha_limite = value;
					this.SendPropertyChanged("fecha_limite");
					this.Onfecha_limiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle_cantidad", DbType="Int NOT NULL")]
		public int detalle_cantidad
		{
			get
			{
				return this._detalle_cantidad;
			}
			set
			{
				if ((this._detalle_cantidad != value))
				{
					this.Ondetalle_cantidadChanging(value);
					this.SendPropertyChanging();
					this._detalle_cantidad = value;
					this.SendPropertyChanged("detalle_cantidad");
					this.Ondetalle_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unitario", DbType="Float NOT NULL")]
		public double precio_unitario
		{
			get
			{
				return this._precio_unitario;
			}
			set
			{
				if ((this._precio_unitario != value))
				{
					this.Onprecio_unitarioChanging(value);
					this.SendPropertyChanging();
					this._precio_unitario = value;
					this.SendPropertyChanged("precio_unitario");
					this.Onprecio_unitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float NOT NULL")]
		public double total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dosificacion")]
	public partial class Dosificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _fecha_registro;
		
		private string _nro_autorizacion;
		
		private string _llave_dosificacion;
		
		private int _NextFactura;
		
		private System.DateTime _fecha_inicio;
		
		private System.DateTime _fecha_limite;
		
		private bool _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    partial void Onnro_autorizacionChanging(string value);
    partial void Onnro_autorizacionChanged();
    partial void Onllave_dosificacionChanging(string value);
    partial void Onllave_dosificacionChanged();
    partial void OnNextFacturaChanging(int value);
    partial void OnNextFacturaChanged();
    partial void Onfecha_inicioChanging(System.DateTime value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_limiteChanging(System.DateTime value);
    partial void Onfecha_limiteChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Dosificacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_autorizacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nro_autorizacion
		{
			get
			{
				return this._nro_autorizacion;
			}
			set
			{
				if ((this._nro_autorizacion != value))
				{
					this.Onnro_autorizacionChanging(value);
					this.SendPropertyChanging();
					this._nro_autorizacion = value;
					this.SendPropertyChanged("nro_autorizacion");
					this.Onnro_autorizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_llave_dosificacion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string llave_dosificacion
		{
			get
			{
				return this._llave_dosificacion;
			}
			set
			{
				if ((this._llave_dosificacion != value))
				{
					this.Onllave_dosificacionChanging(value);
					this.SendPropertyChanging();
					this._llave_dosificacion = value;
					this.SendPropertyChanged("llave_dosificacion");
					this.Onllave_dosificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextFactura", DbType="Int NOT NULL")]
		public int NextFactura
		{
			get
			{
				return this._NextFactura;
			}
			set
			{
				if ((this._NextFactura != value))
				{
					this.OnNextFacturaChanging(value);
					this.SendPropertyChanging();
					this._NextFactura = value;
					this.SendPropertyChanged("NextFactura");
					this.OnNextFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Date NOT NULL")]
		public System.DateTime fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_limite", DbType="Date NOT NULL")]
		public System.DateTime fecha_limite
		{
			get
			{
				return this._fecha_limite;
			}
			set
			{
				if ((this._fecha_limite != value))
				{
					this.Onfecha_limiteChanging(value);
					this.SendPropertyChanging();
					this._fecha_limite = value;
					this.SendPropertyChanged("fecha_limite");
					this.Onfecha_limiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParametroSistemas")]
	public partial class ParametroSistemas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDParametro;
		
		private string _Elemento;
		
		private string _ValorS;
		
		private System.Nullable<int> _ValorI;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDParametroChanging(int value);
    partial void OnIDParametroChanged();
    partial void OnElementoChanging(string value);
    partial void OnElementoChanged();
    partial void OnValorSChanging(string value);
    partial void OnValorSChanged();
    partial void OnValorIChanging(System.Nullable<int> value);
    partial void OnValorIChanged();
    #endregion
		
		public ParametroSistemas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDParametro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDParametro
		{
			get
			{
				return this._IDParametro;
			}
			set
			{
				if ((this._IDParametro != value))
				{
					this.OnIDParametroChanging(value);
					this.SendPropertyChanging();
					this._IDParametro = value;
					this.SendPropertyChanged("IDParametro");
					this.OnIDParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elemento", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Elemento
		{
			get
			{
				return this._Elemento;
			}
			set
			{
				if ((this._Elemento != value))
				{
					this.OnElementoChanging(value);
					this.SendPropertyChanging();
					this._Elemento = value;
					this.SendPropertyChanged("Elemento");
					this.OnElementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorS", DbType="VarChar(100)")]
		public string ValorS
		{
			get
			{
				return this._ValorS;
			}
			set
			{
				if ((this._ValorS != value))
				{
					this.OnValorSChanging(value);
					this.SendPropertyChanging();
					this._ValorS = value;
					this.SendPropertyChanged("ValorS");
					this.OnValorSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorI", DbType="Int")]
		public System.Nullable<int> ValorI
		{
			get
			{
				return this._ValorI;
			}
			set
			{
				if ((this._ValorI != value))
				{
					this.OnValorIChanging(value);
					this.SendPropertyChanging();
					this._ValorI = value;
					this.SendPropertyChanged("ValorI");
					this.OnValorIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
