<?xml version="1.0" encoding="utf-8"?><Database Name="db_dentista" Class="DAgendaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=db_dentista;Integrated Security=True" SettingsObjectName="DAgenda.Properties.Settings" SettingsPropertyName="db_dentistaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dia" Member="Dia">
    <Type Name="Dia">
      <Column Name="iddia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_corto" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Horario" Member="Horario">
    <Type Name="Horario">
      <Column Name="idhorario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="num_horario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="iddia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idempresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioCliente" Member="UsuarioCliente">
    <Type Name="UsuarioCliente">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changepass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NIT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ImageLog" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Trabajos" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IDUsuarioCreador" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Paciente">
    <Type Name="Paciente">
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ci" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nro_telefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_sangre" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cita" Member="Cita">
    <Type Name="Cita">
      <Column Name="idcita" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idempresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="libre" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="atendido" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParametroSistemas" Member="ParametroSistemas">
    <Type Name="ParametroSistemas">
      <Column Name="IDParametro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Elemento" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ValorS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.get_miscitasclient" Method="get_miscitasclient">
    <Parameter Name="PUsuario" Parameter="pUsuario" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="get_miscitasclientResult">
      <Column Name="idcita" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idempresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="libre" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>