#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAgenda
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_dentista")]
	public partial class DAgendaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertHorario(Horario instance);
    partial void UpdateHorario(Horario instance);
    partial void DeleteHorario(Horario instance);
    partial void InsertUsuarioCliente(UsuarioCliente instance);
    partial void UpdateUsuarioCliente(UsuarioCliente instance);
    partial void DeleteUsuarioCliente(UsuarioCliente instance);
    partial void InsertEmpresa(Empresa instance);
    partial void UpdateEmpresa(Empresa instance);
    partial void DeleteEmpresa(Empresa instance);
    partial void InsertCita(Cita instance);
    partial void UpdateCita(Cita instance);
    partial void DeleteCita(Cita instance);
    partial void InsertParametroSistemas(ParametroSistemas instance);
    partial void UpdateParametroSistemas(ParametroSistemas instance);
    partial void DeleteParametroSistemas(ParametroSistemas instance);
    partial void InsertCliente_Paciente(Cliente_Paciente instance);
    partial void UpdateCliente_Paciente(Cliente_Paciente instance);
    partial void DeleteCliente_Paciente(Cliente_Paciente instance);
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    #endregion
		
		public DAgendaDataContext() : 
				base(global::DAgenda.Properties.Settings.Default.db_dentistaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DAgendaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAgendaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAgendaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAgendaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dia> Dia
		{
			get
			{
				return this.GetTable<Dia>();
			}
		}
		
		public System.Data.Linq.Table<Horario> Horario
		{
			get
			{
				return this.GetTable<Horario>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioCliente> UsuarioCliente
		{
			get
			{
				return this.GetTable<UsuarioCliente>();
			}
		}
		
		public System.Data.Linq.Table<Empresa> Empresa
		{
			get
			{
				return this.GetTable<Empresa>();
			}
		}
		
		public System.Data.Linq.Table<Cita> Cita
		{
			get
			{
				return this.GetTable<Cita>();
			}
		}
		
		public System.Data.Linq.Table<ParametroSistemas> ParametroSistemas
		{
			get
			{
				return this.GetTable<ParametroSistemas>();
			}
		}
		
		public System.Data.Linq.Table<Cliente_Paciente> Cliente_Paciente
		{
			get
			{
				return this.GetTable<Cliente_Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Paciente> Paciente
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_miscitasclient")]
		public ISingleResult<get_miscitasclientResult> get_miscitasclient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PUsuario", DbType="NVarChar(50)")] string pUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pUsuario);
			return ((ISingleResult<get_miscitasclientResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dia")]
	public partial class Dia
	{
		
		private int _iddia;
		
		private string _nombre_corto;
		
		private string _descripcion;
		
		public Dia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddia", DbType="Int NOT NULL")]
		public int iddia
		{
			get
			{
				return this._iddia;
			}
			set
			{
				if ((this._iddia != value))
				{
					this._iddia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_corto", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string nombre_corto
		{
			get
			{
				return this._nombre_corto;
			}
			set
			{
				if ((this._nombre_corto != value))
				{
					this._nombre_corto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horario")]
	public partial class Horario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idhorario;
		
		private int _num_horario;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private int _iddia;
		
		private int _idempresa;
		
		private bool _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidhorarioChanging(int value);
    partial void OnidhorarioChanged();
    partial void Onnum_horarioChanging(int value);
    partial void Onnum_horarioChanged();
    partial void Onhora_inicioChanging(System.TimeSpan value);
    partial void Onhora_inicioChanged();
    partial void Onhora_finChanging(System.TimeSpan value);
    partial void Onhora_finChanged();
    partial void OniddiaChanging(int value);
    partial void OniddiaChanged();
    partial void OnidempresaChanging(int value);
    partial void OnidempresaChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Horario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhorario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idhorario
		{
			get
			{
				return this._idhorario;
			}
			set
			{
				if ((this._idhorario != value))
				{
					this.OnidhorarioChanging(value);
					this.SendPropertyChanging();
					this._idhorario = value;
					this.SendPropertyChanged("idhorario");
					this.OnidhorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_horario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int num_horario
		{
			get
			{
				return this._num_horario;
			}
			set
			{
				if ((this._num_horario != value))
				{
					this.Onnum_horarioChanging(value);
					this.SendPropertyChanging();
					this._num_horario = value;
					this.SendPropertyChanged("num_horario");
					this.Onnum_horarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this.Onhora_inicioChanging(value);
					this.SendPropertyChanging();
					this._hora_inicio = value;
					this.SendPropertyChanged("hora_inicio");
					this.Onhora_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this.Onhora_finChanging(value);
					this.SendPropertyChanging();
					this._hora_fin = value;
					this.SendPropertyChanged("hora_fin");
					this.Onhora_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddia", DbType="Int NOT NULL")]
		public int iddia
		{
			get
			{
				return this._iddia;
			}
			set
			{
				if ((this._iddia != value))
				{
					this.OniddiaChanging(value);
					this.SendPropertyChanging();
					this._iddia = value;
					this.SendPropertyChanged("iddia");
					this.OniddiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idempresa", DbType="Int NOT NULL")]
		public int idempresa
		{
			get
			{
				return this._idempresa;
			}
			set
			{
				if ((this._idempresa != value))
				{
					this.OnidempresaChanging(value);
					this.SendPropertyChanging();
					this._idempresa = value;
					this.SendPropertyChanged("idempresa");
					this.OnidempresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioCliente")]
	public partial class UsuarioCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Login;
		
		private string _Password;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Estado;
		
		private System.Nullable<bool> _changepass;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    partial void OnchangepassChanging(System.Nullable<bool> value);
    partial void OnchangepassChanged();
    #endregion
		
		public UsuarioCliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changepass", DbType="Bit")]
		public System.Nullable<bool> changepass
		{
			get
			{
				return this._changepass;
			}
			set
			{
				if ((this._changepass != value))
				{
					this.OnchangepassChanging(value);
					this.SendPropertyChanging();
					this._changepass = value;
					this.SendPropertyChanged("changepass");
					this.OnchangepassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresa")]
	public partial class Empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Login;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _NIT;
		
		private System.Nullable<decimal> _Latitud;
		
		private System.Nullable<decimal> _Longitud;
		
		private System.Data.Linq.Binary _ImageLog;
		
		private System.DateTime _FechaCreacion;
		
		private string _Descripcion;
		
		private string _Trabajos;
		
		private string _IDUsuarioCreador;
		
		private System.Nullable<bool> _Estado;
		
		private string _Email;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    partial void OnLatitudChanging(System.Nullable<decimal> value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(System.Nullable<decimal> value);
    partial void OnLongitudChanged();
    partial void OnImageLogChanging(System.Data.Linq.Binary value);
    partial void OnImageLogChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnTrabajosChanging(string value);
    partial void OnTrabajosChanged();
    partial void OnIDUsuarioCreadorChanging(string value);
    partial void OnIDUsuarioCreadorChanged();
    partial void OnEstadoChanging(System.Nullable<bool> value);
    partial void OnEstadoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Empresa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this.OnLatitudChanging(value);
					this.SendPropertyChanging();
					this._Latitud = value;
					this.SendPropertyChanged("Latitud");
					this.OnLatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this.OnLongitudChanging(value);
					this.SendPropertyChanging();
					this._Longitud = value;
					this.SendPropertyChanged("Longitud");
					this.OnLongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageLog", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImageLog
		{
			get
			{
				return this._ImageLog;
			}
			set
			{
				if ((this._ImageLog != value))
				{
					this.OnImageLogChanging(value);
					this.SendPropertyChanging();
					this._ImageLog = value;
					this.SendPropertyChanged("ImageLog");
					this.OnImageLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trabajos", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Trabajos
		{
			get
			{
				return this._Trabajos;
			}
			set
			{
				if ((this._Trabajos != value))
				{
					this.OnTrabajosChanging(value);
					this.SendPropertyChanging();
					this._Trabajos = value;
					this.SendPropertyChanged("Trabajos");
					this.OnTrabajosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuarioCreador", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IDUsuarioCreador
		{
			get
			{
				return this._IDUsuarioCreador;
			}
			set
			{
				if ((this._IDUsuarioCreador != value))
				{
					this.OnIDUsuarioCreadorChanging(value);
					this.SendPropertyChanging();
					this._IDUsuarioCreador = value;
					this.SendPropertyChanged("IDUsuarioCreador");
					this.OnIDUsuarioCreadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cita")]
	public partial class Cita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idcita;
		
		private System.DateTime _fecha;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private string _id_cliente;
		
		private int _idempresa;
		
		private bool _estado;
		
		private bool _libre;
		
		private System.Nullable<bool> _atendido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcitaChanging(string value);
    partial void OnidcitaChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onhora_inicioChanging(System.TimeSpan value);
    partial void Onhora_inicioChanged();
    partial void Onhora_finChanging(System.TimeSpan value);
    partial void Onhora_finChanged();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    partial void OnidempresaChanging(int value);
    partial void OnidempresaChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    partial void OnlibreChanging(bool value);
    partial void OnlibreChanged();
    partial void OnatendidoChanging(System.Nullable<bool> value);
    partial void OnatendidoChanged();
    #endregion
		
		public Cita()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcita", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idcita
		{
			get
			{
				return this._idcita;
			}
			set
			{
				if ((this._idcita != value))
				{
					this.OnidcitaChanging(value);
					this.SendPropertyChanging();
					this._idcita = value;
					this.SendPropertyChanged("idcita");
					this.OnidcitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this.Onhora_inicioChanging(value);
					this.SendPropertyChanging();
					this._hora_inicio = value;
					this.SendPropertyChanged("hora_inicio");
					this.Onhora_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this.Onhora_finChanging(value);
					this.SendPropertyChanging();
					this._hora_fin = value;
					this.SendPropertyChanged("hora_fin");
					this.Onhora_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idempresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idempresa
		{
			get
			{
				return this._idempresa;
			}
			set
			{
				if ((this._idempresa != value))
				{
					this.OnidempresaChanging(value);
					this.SendPropertyChanging();
					this._idempresa = value;
					this.SendPropertyChanged("idempresa");
					this.OnidempresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libre", DbType="Bit NOT NULL")]
		public bool libre
		{
			get
			{
				return this._libre;
			}
			set
			{
				if ((this._libre != value))
				{
					this.OnlibreChanging(value);
					this.SendPropertyChanging();
					this._libre = value;
					this.SendPropertyChanged("libre");
					this.OnlibreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atendido", DbType="Bit")]
		public System.Nullable<bool> atendido
		{
			get
			{
				return this._atendido;
			}
			set
			{
				if ((this._atendido != value))
				{
					this.OnatendidoChanging(value);
					this.SendPropertyChanging();
					this._atendido = value;
					this.SendPropertyChanged("atendido");
					this.OnatendidoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParametroSistemas")]
	public partial class ParametroSistemas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDParametro;
		
		private string _Elemento;
		
		private string _ValorS;
		
		private System.Nullable<int> _ValorI;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDParametroChanging(int value);
    partial void OnIDParametroChanged();
    partial void OnElementoChanging(string value);
    partial void OnElementoChanged();
    partial void OnValorSChanging(string value);
    partial void OnValorSChanged();
    partial void OnValorIChanging(System.Nullable<int> value);
    partial void OnValorIChanged();
    #endregion
		
		public ParametroSistemas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDParametro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDParametro
		{
			get
			{
				return this._IDParametro;
			}
			set
			{
				if ((this._IDParametro != value))
				{
					this.OnIDParametroChanging(value);
					this.SendPropertyChanging();
					this._IDParametro = value;
					this.SendPropertyChanged("IDParametro");
					this.OnIDParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elemento", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Elemento
		{
			get
			{
				return this._Elemento;
			}
			set
			{
				if ((this._Elemento != value))
				{
					this.OnElementoChanging(value);
					this.SendPropertyChanging();
					this._Elemento = value;
					this.SendPropertyChanged("Elemento");
					this.OnElementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorS", DbType="VarChar(100)")]
		public string ValorS
		{
			get
			{
				return this._ValorS;
			}
			set
			{
				if ((this._ValorS != value))
				{
					this.OnValorSChanging(value);
					this.SendPropertyChanging();
					this._ValorS = value;
					this.SendPropertyChanged("ValorS");
					this.OnValorSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorI", DbType="Int")]
		public System.Nullable<int> ValorI
		{
			get
			{
				return this._ValorI;
			}
			set
			{
				if ((this._ValorI != value))
				{
					this.OnValorIChanging(value);
					this.SendPropertyChanging();
					this._ValorI = value;
					this.SendPropertyChanged("ValorI");
					this.OnValorIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente_Paciente")]
	public partial class Cliente_Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_usuariocliente;
		
		private int _id_paciente;
		
		private System.Nullable<bool> _IsPrincipal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioclienteChanging(string value);
    partial void Onid_usuarioclienteChanged();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnIsPrincipalChanging(System.Nullable<bool> value);
    partial void OnIsPrincipalChanged();
    #endregion
		
		public Cliente_Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_usuariocliente
		{
			get
			{
				return this._id_usuariocliente;
			}
			set
			{
				if ((this._id_usuariocliente != value))
				{
					this.Onid_usuarioclienteChanging(value);
					this.SendPropertyChanging();
					this._id_usuariocliente = value;
					this.SendPropertyChanged("id_usuariocliente");
					this.Onid_usuarioclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrincipal", DbType="Bit")]
		public System.Nullable<bool> IsPrincipal
		{
			get
			{
				return this._IsPrincipal;
			}
			set
			{
				if ((this._IsPrincipal != value))
				{
					this.OnIsPrincipalChanging(value);
					this.SendPropertyChanging();
					this._IsPrincipal = value;
					this.SendPropertyChanged("IsPrincipal");
					this.OnIsPrincipalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paciente")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paciente;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _ci;
		
		private string _nro_telefono;
		
		private string _direccion;
		
		private string _email;
		
		private string _tipo_sangre;
		
		private char _sexo;
		
		private bool _estado;
		
		private string _antecedente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnciChanging(string value);
    partial void OnciChanged();
    partial void Onnro_telefonoChanging(string value);
    partial void Onnro_telefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ontipo_sangreChanging(string value);
    partial void Ontipo_sangreChanged();
    partial void OnsexoChanging(char value);
    partial void OnsexoChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    partial void OnantecedenteChanging(string value);
    partial void OnantecedenteChanged();
    #endregion
		
		public Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="VarChar(10)")]
		public string ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this.OnciChanging(value);
					this.SendPropertyChanging();
					this._ci = value;
					this.SendPropertyChanged("ci");
					this.OnciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_telefono", DbType="VarChar(10)")]
		public string nro_telefono
		{
			get
			{
				return this._nro_telefono;
			}
			set
			{
				if ((this._nro_telefono != value))
				{
					this.Onnro_telefonoChanging(value);
					this.SendPropertyChanging();
					this._nro_telefono = value;
					this.SendPropertyChanged("nro_telefono");
					this.Onnro_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sangre", DbType="VarChar(4)")]
		public string tipo_sangre
		{
			get
			{
				return this._tipo_sangre;
			}
			set
			{
				if ((this._tipo_sangre != value))
				{
					this.Ontipo_sangreChanging(value);
					this.SendPropertyChanging();
					this._tipo_sangre = value;
					this.SendPropertyChanged("tipo_sangre");
					this.Ontipo_sangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antecedente", DbType="NVarChar(1000)")]
		public string antecedente
		{
			get
			{
				return this._antecedente;
			}
			set
			{
				if ((this._antecedente != value))
				{
					this.OnantecedenteChanging(value);
					this.SendPropertyChanging();
					this._antecedente = value;
					this.SendPropertyChanged("antecedente");
					this.OnantecedenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class get_miscitasclientResult
	{
		
		private string _idcita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private string _id_cliente;
		
		private int _idempresa;
		
		private bool _estado;
		
		private bool _libre;
		
		private string _Nombre;
		
		public get_miscitasclientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcita", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string idcita
		{
			get
			{
				return this._idcita;
			}
			set
			{
				if ((this._idcita != value))
				{
					this._idcita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this._hora_inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this._hora_fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this._id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idempresa", DbType="Int NOT NULL")]
		public int idempresa
		{
			get
			{
				return this._idempresa;
			}
			set
			{
				if ((this._idempresa != value))
				{
					this._idempresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libre", DbType="Bit NOT NULL")]
		public bool libre
		{
			get
			{
				return this._libre;
			}
			set
			{
				if ((this._libre != value))
				{
					this._libre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
