<?xml version="1.0" encoding="utf-8"?><Database Name="db_dentista" Class="DLoginLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=db_dentista;Integrated Security=True" SettingsObjectName="DLogin.Properties.Settings" SettingsPropertyName="db_dentistaConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Direccion" Member="Direccion">
    <Type Name="Direccion">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Member="Direccion1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Componente" Member="Rol_Componente">
    <Type Name="Rol_Componente">
      <Column Name="ID_Rol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Componente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Formulario" Member="Rol_Formulario">
    <Type Name="Rol_Formulario">
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDFormulario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Modulo" Member="Rol_Modulo">
    <Type Name="Rol_Modulo">
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDModulo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa_Cliente" Member="Empresa_Cliente">
    <Type Name="Empresa_Cliente">
      <Column Name="id_empresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_usuariocliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Modulo" Member="Modulo">
    <Type Name="Modulo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fomulario" Member="Fomulario">
    <Type Name="Fomulario">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDModulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Componente" Member="Componente">
    <Type Name="Componente">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDFormulario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Envio" Member="Envio">
    <Type Name="Envio">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Contador" Member="Contador">
    <Type Name="Contador">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hora" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioEmpleado" Member="UsuarioEmpleado">
    <Type Name="UsuarioEmpleado">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changepass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioCliente" Member="UsuarioCliente">
    <Type Name="UsuarioCliente">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changepass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Paciente">
    <Type Name="Paciente">
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ci" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nro_telefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_sangre" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="antecedente" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Planilla_Vendedores" Member="Planilla_Vendedores">
    <Type Name="Planilla_Vendedores">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MontoTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ParametroSistemas" Member="ParametroSistemas">
    <Type Name="ParametroSistemas">
      <Column Name="IDParametro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Elemento" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ValorS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tiempo_Consulta" Member="Tiempo_Consulta">
    <Type Name="Tiempo_Consulta">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Licencia" Member="Licencia">
    <Type Name="Licencia">
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NIT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaModificacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuarioCreador" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDIntervalo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clinica" Member="Clinica">
    <Type Name="Clinica">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ImagenLogo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuarioCreacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaDeModificacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CantidadConsultorios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TrabajosConsultorio" Member="TrabajosConsultorio">
    <Type Name="TrabajosConsultorio">
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTrabajo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Trabajos" Member="Trabajos">
    <Type Name="Trabajos">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Telefono" Member="Telefono">
    <Type Name="Telefono">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Member="Telefono1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TefonosClinica" Member="TefonosClinica">
    <Type Name="TefonosClinica">
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTelefono" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TelefonoConsultorio" Member="TelefonoConsultorio">
    <Type Name="TelefonoConsultorio">
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTelefono" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TipoNotificacion" Member="TipoNotificacion">
    <Type Name="TipoNotificacion">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NotificacionConsultorio" Member="NotificacionConsultorio">
    <Type Name="NotificacionConsultorio">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TipoNotificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente_Paciente" Member="Cliente_Paciente">
    <Type Name="Cliente_Paciente">
      <Column Name="id_usuariocliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsPrincipal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.getComponentes" Method="getComponentes">
    <Parameter Name="IDFormulario" Parameter="iDFormulario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dacasys" Parameter="dacasys" Type="System.Int32" DbType="Int" />
    <ElementType Name="getComponentesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDFormulario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Si_Pertenece" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getFormularios" Method="getFormularios">
    <Parameter Name="IDModulo" Parameter="iDModulo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dacasys" Parameter="dacasys" Type="System.Int32" DbType="Int" />
    <ElementType Name="getFormulariosResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDModulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Si_Pertenece" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Buscar_Empresa_Horario" Method="Buscar_Empresa_Horario">
    <Parameter Name="PFecha" Parameter="pFecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="PHora" Parameter="pHora" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="NroDia" Parameter="nroDia" Type="System.Int32" DbType="Int" />
    <Parameter Name="PUsuario" Parameter="pUsuario" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Buscar_Empresa_HorarioResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NIT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getModulos" Method="getModulos">
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="dacasys" Type="System.Int32" DbType="Int" />
    <ElementType Name="getModulosResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Si_Pertenece" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getIDEmpresas" Method="getIDEmpresas">
    <ElementType Name="getIDEmpresasResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CleanLog" Method="CleanLog">
    <Return Type="System.Int32" />
  </Function>
</Database>