(function(v){function K(a,b){return function(c){return l(a.call(this,c),b)}}function ca(a,b){return function(c){return this.lang().ordinal(a.call(this,c),b)}}function L(){}function w(a){r(this,a)}function B(a){var b=M(a),c=b.year||0,e=b.month||0,d=b.week||0,h=b.day||0,g=b.hour||0,k=b.minute||0,l=b.second||0,b=b.millisecond||0;this._input=a;this._milliseconds=+b+1E3*l+6E4*k+36E5*g;this._days=+h+7*d;this._months=+e+12*c;this._data={};this._bubble()}function r(a,b){for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c]);b.hasOwnProperty("toString")&&(a.toString=b.toString);b.hasOwnProperty("valueOf")&&(a.valueOf=b.valueOf);return a}function q(a){return 0>a?Math.ceil(a):Math.floor(a)}function l(a,b){for(var c=a+"";c.length<b;)c="0"+c;return c}function C(a,b,c,e){var f=b._milliseconds,h=b._days;b=b._months;var g,k;f&&a._d.setTime(+a._d+f*c);if(h||b)g=a.minute(),k=a.hour();h&&a.date(a.date()+h*c);b&&a.month(a.month()+b*c);f&&!e&&d.updateOffset(a);if(h||b)a.minute(g),a.hour(k)}function N(a,b){var c=Math.min(a.length,
b.length),e=Math.abs(a.length-b.length),d=0,h;for(h=0;h<c;h++)g(a[h])!==g(b[h])&&d++;return d+e}function n(a){return a?da[a]||a.toLowerCase().replace(/(.)s$/,"$1"):a}function M(a){var b={},c,e;for(e in a)a.hasOwnProperty(e)&&(c=n(e))&&(b[c]=a[e]);return b}function ea(a){var b,c;if(0===a.indexOf("week"))b=7,c="day";else if(0===a.indexOf("month"))b=12,c="month";else return;d[a]=function(e,f){var h,g,k=d.fn._lang[a],l=[];"number"===typeof e&&(f=e,e=v);g=function(a){a=d().utc().set(c,a);return k.call(d.fn._lang,
a,e||"")};if(f)return g(f);for(h=0;h<b;h++)l.push(g(h));return l}}function g(a){a=+a;var b=0;0!==a&&isFinite(a)&&(b=0<=a?Math.floor(a):Math.ceil(a));return b}function p(a){if(!a)return d.fn._lang;if(!t[a]&&O)try{require("./lang/"+a)}catch(b){return d.fn._lang}return t[a]||d.fn._lang}function fa(a){return a.match(/\[.*\]/)?a.replace(/^\[|\]$/g,""):a.replace(/\\/g,"")}function ga(a){var b=a.match(x),c,e;c=0;for(e=b.length;c<e;c++)b[c]=m[b[c]]?m[b[c]]:fa(b[c]);return function(d){var h="";for(c=0;c<e;c++)h+=
b[c]instanceof Function?b[c].call(d,a):b[c];return h}}function P(a,b){b=Q(b,a.lang());D[b]||(D[b]=ga(b));return D[b](a)}function Q(a,b){function c(a){return b.longDateFormat(a)||a}var e=5;for(y.lastIndex=0;0<=e&&y.test(a);)a=a.replace(y,c),y.lastIndex=0,--e;return a}function R(a,b){switch(a){case "DDDD":return ha;case "YYYY":return ia;case "YYYYY":return ja;case "S":case "SS":case "SSS":case "DDD":return ka;case "MMM":case "MMMM":case "dd":case "ddd":case "dddd":return la;case "a":case "A":return p(b._l)._meridiemParse;
case "X":return ma;case "Z":case "ZZ":return E;case "T":return na;case "MM":case "DD":case "YY":case "HH":case "hh":case "mm":case "ss":case "M":case "D":case "d":case "H":case "h":case "m":case "s":return oa;default:return new RegExp(F(a.replace("\\","")))}}function S(a){a=((E.exec(a)||[])[0]+"").match(pa)||["-",0,0];var b=+(60*a[1])+g(a[2]);return"+"===a[0]?-b:b}function T(a,b,c){var e=c._a;switch(a){case "M":case "MM":null!=b&&(e[1]=g(b)-1);break;case "MMM":case "MMMM":a=p(c._l).monthsParse(b);
null!=a?e[1]=a:c._isValid=!1;break;case "D":case "DD":null!=b&&(e[2]=g(b));break;case "DDD":case "DDDD":null!=b&&(e[1]=0,e[2]=g(b));break;case "YY":e[0]=g(b)+(68<g(b)?1900:2E3);break;case "YYYY":case "YYYYY":e[0]=g(b);break;case "a":case "A":c._isPm=p(c._l).isPM(b);break;case "H":case "HH":case "h":case "hh":e[3]=g(b);break;case "m":case "mm":e[4]=g(b);break;case "s":case "ss":e[5]=g(b);break;case "S":case "SS":case "SSS":e[6]=g(1E3*("0."+b));break;case "X":c._d=new Date(1E3*parseFloat(b));c._isValid=
!isNaN(c._d.getTime());break;case "Z":case "ZZ":c._useUTC=!0,c._tzm=S(b)}null==b&&(c._isValid=!1)}function z(a){var b,c=[],e;if(!a._d){b=new Date;e=a._useUTC?[b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate()]:[b.getFullYear(),b.getMonth(),b.getDate()];for(b=0;3>b&&null==a._a[b];++b)a._a[b]=c[b]=e[b];for(;7>b;b++)a._a[b]=c[b]=null==a._a[b]?2===b?1:0:a._a[b];c[3]+=g((a._tzm||0)/60);c[4]+=g((a._tzm||0)%60);b=new Date(0);a._useUTC?(b.setUTCFullYear(c[0],c[1],c[2]),b.setUTCHours(c[3],c[4],c[5],c[6])):
(b.setFullYear(c[0],c[1],c[2]),b.setHours(c[3],c[4],c[5],c[6]));a._d=b}}function G(a){if(a._strict)qa(a);else{var b=p(a._l),c=""+a._i,e,d,h=c.length,g=0;d=Q(a._f,b).match(x);a._a=[];for(b=0;b<d.length;b++){if(e=(R(d[b],a).exec(c)||[])[0])c=c.slice(c.indexOf(e)+e.length),g+=e.length;m[d[b]]&&T(d[b],e,a)}a._il=h-g;a._isPm&&12>a._a[3]&&(a._a[3]+=12);!1===a._isPm&&12===a._a[3]&&(a._a[3]=0);z(a)}}function qa(a){var b="",c=0,e=a._f.match(x),d,h,g;a._f.replace(x,function(d){var e=arguments[arguments.length-
2],f;m[d]&&(f=R(d).toString(),f=f.replace(/\(/g,"(?:"),e>c&&(b+=F(U(a._f.substring(c,e)))),c=e+d.length,b+="("+f.substring(1,f.lastIndexOf("/"))+")");return d});c!==a._f.length&&(b+=F(U(a._f.substring(c))));b=new RegExp("^"+b+"$");d=a._i.match(b);if(null===d)a._a=[],a._d=new Date(0),a._isValid=!1;else{a._a=[];for(h=g=0;h<e.length;++h)m[e[h]]&&(T(e[h],d[g+1],a),++g);z(a)}}function U(a){return a.replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g,function(a,c,d,f,h){return c||d||f||h})}function F(a){return a.replace(/[-\/\\^$*+?.()|[\]{}]/g,
"\\$&")}function ra(a,b,c,d,f){return f.relativeTime(b||1,!!c,a,d)}function A(a,b,c){b=c-b;c-=a.day();c>b&&(c-=7);c<b-7&&(c+=7);a=d(a).add("d",c);return{week:Math.ceil(a.dayOfYear()/7),year:a.year()}}function V(a){var b=a._i,c=a._f;if(null===b||""===b)return d.invalid();"string"===typeof b&&(a._i=b=p().preparse(b));if(d.isMoment(b))a=r({},b),a._d=new Date(+b._d);else if(c)if("[object Array]"===Object.prototype.toString.call(c)){var b=a,e,f,h=99,g;for(g=0;g<b._f.length;g++)e=r({},b),e._f=b._f[g],G(e),
c=new w(e),e=N(e._a,c.toArray()),e+=c._il||0,e<h&&(h=e,f=c);r(b,f)}else G(a);else if(f=a,b=f._i,c=sa.exec(b),b===v)f._d=new Date;else if(c)f._d=new Date(+c[1]);else if("string"===typeof b)if(b=f._i,c=ta.exec(b)){f._f="YYYY-MM-DD"+(c[2]||" ");for(c=0;4>c;c++)if(W[c][1].exec(b)){f._f+=W[c][0];break}E.exec(b)&&(f._f+=" Z");G(f)}else f._d=new Date(b);else"[object Array]"===Object.prototype.toString.call(b)?(f._a=b.slice(0),z(f)):"[object Date]"===Object.prototype.toString.call(b)?f._d=new Date(+b):"object"===
typeof b?f._d||(b=M(f._i),f._a=[b.year,b.month,b.day,b.hour,b.minute,b.second,b.millisecond],z(f)):f._d=new Date(b);return new w(a)}function X(a,b){d.fn[a]=d.fn[a+"s"]=function(a){var e=this._isUTC?"UTC":"";return null!=a?(this._d["set"+e+b](a),d.updateOffset(this),this):this._d["get"+e+b]()}}function ua(a){d.duration.fn[a]=function(){return this._data[a]}}function Y(a,b){d.duration.fn["as"+a]=function(){return+this/b}}function H(){"undefined"===typeof ender&&(this.moment=d)}for(var d,u=Math.round,
k,t={},O="undefined"!==typeof module&&module.exports,sa=/^\/?Date\((\-?\d+)/i,va=/(\-)?(?:(\d*)\.)?(\d+)\:(\d+)(?:\:(\d+)\.?(\d{3})?)?/,x=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|mm?|ss?|SS?S?|X|zz?|ZZ?|.)/g,y=/(\[[^\[]*\])|(\\)?(LT|LL?L?L?|l{1,4})/g,oa=/\d\d?/,ka=/\d{1,3}/,ha=/\d{3}/,ia=/\d{1,4}/,ja=/[+\-]?\d{1,6}/,la=/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i,
E=/Z|[\+\-]\d\d:?\d\d/i,na=/T/i,ma=/[\+\-]?\d+(\.\d{1,3})?/,ta=/^\s*\d{4}-\d\d-\d\d((T| )(\d\d(:\d\d(:\d\d(\.\d\d?\d?)?)?)?)?([\+\-]\d\d:?\d\d)?)?$/,W=[["HH:mm:ss.S",/(T| )\d\d:\d\d:\d\d\.\d{1,3}/],["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],pa=/([\+\-]|\d\d)/gi,I=["Date","Hours","Minutes","Seconds","Milliseconds"],J={Milliseconds:1,Seconds:1E3,Minutes:6E4,Hours:36E5,Days:864E5,Months:2592E6,Years:31536E6},da={ms:"millisecond",s:"second",m:"minute",h:"hour",d:"day",
w:"week",W:"isoweek",M:"month",y:"year"},D={},Z="DDD w W M D d".split(" "),aa="MDHhmswW".split(""),m={M:function(){return this.month()+1},MMM:function(a){return this.lang().monthsShort(this,a)},MMMM:function(a){return this.lang().months(this,a)},D:function(){return this.date()},DDD:function(){return this.dayOfYear()},d:function(){return this.day()},dd:function(a){return this.lang().weekdaysMin(this,a)},ddd:function(a){return this.lang().weekdaysShort(this,a)},dddd:function(a){return this.lang().weekdays(this,
a)},w:function(){return this.week()},W:function(){return this.isoWeek()},YY:function(){return l(this.year()%100,2)},YYYY:function(){return l(this.year(),4)},YYYYY:function(){return l(this.year(),5)},gg:function(){return l(this.weekYear()%100,2)},gggg:function(){return this.weekYear()},ggggg:function(){return l(this.weekYear(),5)},GG:function(){return l(this.isoWeekYear()%100,2)},GGGG:function(){return this.isoWeekYear()},GGGGG:function(){return l(this.isoWeekYear(),5)},e:function(){return this.weekday()},
E:function(){return this.isoWeekday()},a:function(){return this.lang().meridiem(this.hours(),this.minutes(),!0)},A:function(){return this.lang().meridiem(this.hours(),this.minutes(),!1)},H:function(){return this.hours()},h:function(){return this.hours()%12||12},m:function(){return this.minutes()},s:function(){return this.seconds()},S:function(){return g(this.milliseconds()/100)},SS:function(){return l(g(this.milliseconds()/10),2)},SSS:function(){return l(this.milliseconds(),3)},Z:function(){var a=
-this.zone(),b="+";0>a&&(a=-a,b="-");return b+l(g(a/60),2)+":"+l(g(a)%60,2)},ZZ:function(){var a=-this.zone(),b="+";0>a&&(a=-a,b="-");return b+l(g(10*a/6),4)},z:function(){return this.zoneAbbr()},zz:function(){return this.zoneName()},X:function(){return this.unix()}},ba=["months","monthsShort","weekdays","weekdaysShort","weekdaysMin"];Z.length;)k=Z.pop(),m[k+"o"]=ca(m[k],k);for(;aa.length;)k=aa.pop(),m[k+k]=K(m[k],2);m.DDDD=K(m.DDD,3);r(L.prototype,{set:function(a){var b,c;for(c in a)b=a[c],"function"===
typeof b?this[c]=b:this["_"+c]=b},_months:"January February March April May June July August September October November December".split(" "),months:function(a){return this._months[a.month()]},_monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),monthsShort:function(a){return this._monthsShort[a.month()]},monthsParse:function(a){var b,c;this._monthsParse||(this._monthsParse=[]);for(b=0;12>b;b++)if(this._monthsParse[b]||(c=d.utc([2E3,b]),c="^"+this.months(c,"")+"|^"+this.monthsShort(c,
""),this._monthsParse[b]=new RegExp(c.replace(".",""),"i")),this._monthsParse[b].test(a))return b},_weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdays:function(a){return this._weekdays[a.day()]},_weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),weekdaysShort:function(a){return this._weekdaysShort[a.day()]},_weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),weekdaysMin:function(a){return this._weekdaysMin[a.day()]},weekdaysParse:function(a){var b,c;this._weekdaysParse||
(this._weekdaysParse=[]);for(b=0;7>b;b++)if(this._weekdaysParse[b]||(c=d([2E3,1]).day(b),c="^"+this.weekdays(c,"")+"|^"+this.weekdaysShort(c,"")+"|^"+this.weekdaysMin(c,""),this._weekdaysParse[b]=new RegExp(c.replace(".",""),"i")),this._weekdaysParse[b].test(a))return b},_longDateFormat:{LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D YYYY",LLL:"MMMM D YYYY LT",LLLL:"dddd, MMMM D YYYY LT"},longDateFormat:function(a){var b=this._longDateFormat[a];!b&&this._longDateFormat[a.toUpperCase()]&&(b=this._longDateFormat[a.toUpperCase()].replace(/MMMM|MM|DD|dddd/g,
function(a){return a.slice(1)}),this._longDateFormat[a]=b);return b},isPM:function(a){return"p"===(a+"").toLowerCase().charAt(0)},_meridiemParse:/[ap]\.?m?\.?/i,meridiem:function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"},_calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[Last] dddd [at] LT",sameElse:"L"},calendar:function(a,b){var c=this._calendar[a];return"function"===typeof c?c.apply(b):c},_relativeTime:{future:"in %s",
past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},relativeTime:function(a,b,c,d){var f=this._relativeTime[c];return"function"===typeof f?f(a,b,c,d):f.replace(/%d/i,a)},pastFuture:function(a,b){var c=this._relativeTime[0<a?"future":"past"];return"function"===typeof c?c(b):c.replace(/%s/i,b)},ordinal:function(a){return this._ordinal.replace("%d",a)},_ordinal:"%d",preparse:function(a){return a},
postformat:function(a){return a},week:function(a){return A(a,this._week.dow,this._week.doy).week},_week:{dow:0,doy:6}});d=function(a,b,c,d){"boolean"===typeof c&&(d=c,c=v);return V({_i:a,_f:b,_l:c,_strict:d,_isUTC:!1})};d.utc=function(a,b,c,d){"boolean"===typeof c&&(d=c,c=v);a=V({_useUTC:!0,_isUTC:!0,_l:c,_i:a,_f:b,_strict:d});null!=a&&(a=a.utc());return a};d.unix=function(a){return d(1E3*a)};d.duration=function(a,b){var c=d.isDuration(a),e="number"===typeof a,f=c?a._input:e?{}:a,h=va.exec(a);e?b?
f[b]=a:f.milliseconds=a:h&&(e="-"===h[1]?-1:1,f={y:0,d:g(h[2])*e,h:g(h[3])*e,m:g(h[4])*e,s:g(h[5])*e,ms:g(h[6])*e});h=new B(f);c&&a.hasOwnProperty("_lang")&&(h._lang=a._lang);return h};d.version="2.2.1";d.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";d.updateOffset=function(){};d.lang=function(a,b){if(!a)return d.fn._lang._abbr;a=a.toLowerCase();a=a.replace("_","-");if(b){var c=a;b.abbr=c;t[c]||(t[c]=new L);t[c].set(b)}else null===b?(delete t[a],a="en"):t[a]||p(a);d.duration.fn._lang=d.fn._lang=p(a)};d.langData=
function(a){a&&a._lang&&a._lang._abbr&&(a=a._lang._abbr);return p(a)};d.isMoment=function(a){return a instanceof w};d.isDuration=function(a){return a instanceof B};for(k in ba)ea(ba[k]);d.normalizeUnits=function(a){return n(a)};d.invalid=function(){var a=d.utc(NaN);a._isValid=!1;return a};d.parseZone=function(a){return d(a).parseZone()};r(d.fn=w.prototype,{clone:function(){return d(this)},valueOf:function(){return+this._d+6E4*(this._offset||0)},unix:function(){return Math.floor(+this/1E3)},toString:function(){return this.clone().lang("en").format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")},
toDate:function(){return this._offset?new Date(+this):this._d},toISOString:function(){return P(d(this).utc(),"YYYY-MM-DD[T]HH:mm:ss.SSS[Z]")},toArray:function(){return[this.year(),this.month(),this.date(),this.hours(),this.minutes(),this.seconds(),this.milliseconds()]},isValid:function(){null==this._isValid&&(this._isValid=this._a?!N(this._a,(this._isUTC?d.utc(this._a):d(this._a)).toArray()):!isNaN(this._d.getTime()));return!!this._isValid},invalidAt:function(){var a,b=this._a,c=(this._isUTC?d.utc(this._a):
d(this._a)).toArray();for(a=6;0<=a&&b[a]===c[a];--a);return a},utc:function(){return this.zone(0)},local:function(){this.zone(0);this._isUTC=!1;return this},format:function(a){a=P(this,a||d.defaultFormat);return this.lang().postformat(a)},add:function(a,b){var c;c="string"===typeof a?d.duration(+b,a):d.duration(a,b);C(this,c,1);return this},subtract:function(a,b){var c;c="string"===typeof a?d.duration(+b,a):d.duration(a,b);C(this,c,-1);return this},diff:function(a,b,c){a=this._isUTC?d(a).zone(this._offset||
0):d(a).local();var e=6E4*(this.zone()-a.zone()),f;b=n(b);"year"===b||"month"===b?(f=432E5*(this.daysInMonth()+a.daysInMonth()),e=12*(this.year()-a.year())+(this.month()-a.month()),e+=(this-d(this).startOf("month")-(a-d(a).startOf("month")))/f,e-=6E4*(this.zone()-d(this).startOf("month").zone()-(a.zone()-d(a).startOf("month").zone()))/f,"year"===b&&(e/=12)):(f=this-a,e="second"===b?f/1E3:"minute"===b?f/6E4:"hour"===b?f/36E5:"day"===b?(f-e)/864E5:"week"===b?(f-e)/6048E5:f);return c?e:q(e)},from:function(a,
b){return d.duration(this.diff(a)).lang(this.lang()._abbr).humanize(!b)},fromNow:function(a){return this.from(d(),a)},calendar:function(){var a=this.diff(d().zone(this.zone()).startOf("day"),"days",!0),a=-6>a?"sameElse":-1>a?"lastWeek":0>a?"lastDay":1>a?"sameDay":2>a?"nextDay":7>a?"nextWeek":"sameElse";return this.format(this.lang().calendar(a,this))},isLeapYear:function(){var a=this.year();return 0===a%4&&0!==a%100||0===a%400},isDST:function(){return this.zone()<this.clone().month(0).zone()||this.zone()<
this.clone().month(5).zone()},day:function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();return null!=a?"string"===typeof a&&(a=this.lang().weekdaysParse(a),"number"!==typeof a)?this:this.add({d:a-b}):b},month:function(a){var b=this._isUTC?"UTC":"",c;if(null!=a){if("string"===typeof a&&(a=this.lang().monthsParse(a),"number"!==typeof a))return this;c=this.date();this.date(1);this._d["set"+b+"Month"](a);this.date(Math.min(c,this.daysInMonth()));d.updateOffset(this);return this}return this._d["get"+
b+"Month"]()},startOf:function(a){a=n(a);switch(a){case "year":this.month(0);case "month":this.date(1);case "week":case "isoweek":case "day":this.hours(0);case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a?this.weekday(0):"isoweek"===a&&this.isoWeekday(1);return this},endOf:function(a){a=n(a);return this.startOf(a).add("isoweek"===a?"week":a,1).subtract("ms",1)},isAfter:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)>
+d(a).startOf(b)},isBefore:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)<+d(a).startOf(b)},isSame:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)===+d(a).startOf(b)},min:function(a){a=d.apply(null,arguments);return a<this?this:a},max:function(a){a=d.apply(null,arguments);return a>this?this:a},zone:function(a){var b=this._offset||0;if(null!=a)"string"===typeof a&&(a=S(a)),16>Math.abs(a)&&(a*=60),this._offset=a,this._isUTC=
!0,b!==a&&C(this,d.duration(b-a,"m"),1,!0);else return this._isUTC?b:this._d.getTimezoneOffset();return this},zoneAbbr:function(){return this._isUTC?"UTC":""},zoneName:function(){return this._isUTC?"Coordinated Universal Time":""},parseZone:function(){"string"===typeof this._i&&this.zone(this._i);return this},hasAlignedHourOffset:function(a){a=a?d(a).zone():0;return 0===(this.zone()-a)%60},daysInMonth:function(){return d.utc([this.year(),this.month()+1,0]).date()},dayOfYear:function(a){var b=u((d(this).startOf("day")-
d(this).startOf("year"))/864E5)+1;return null==a?b:this.add("d",a-b)},weekYear:function(a){var b=A(this,this.lang()._week.dow,this.lang()._week.doy).year;return null==a?b:this.add("y",a-b)},isoWeekYear:function(a){var b=A(this,1,4).year;return null==a?b:this.add("y",a-b)},week:function(a){var b=this.lang().week(this);return null==a?b:this.add("d",7*(a-b))},isoWeek:function(a){var b=A(this,1,4).week;return null==a?b:this.add("d",7*(a-b))},weekday:function(a){var b=(this.day()+7-this.lang()._week.dow)%
7;return null==a?b:this.add("d",a-b)},isoWeekday:function(a){return null==a?this.day()||7:this.day(this.day()%7?a:a-7)},get:function(a){a=n(a);return this[a.toLowerCase()]()},set:function(a,b){a=n(a);this[a.toLowerCase()](b);return this},lang:function(a){if(a===v)return this._lang;this._lang=p(a);return this}});for(k=0;k<I.length;k++)X(I[k].toLowerCase().replace(/s$/,""),I[k]);X("year","FullYear");d.fn.days=d.fn.day;d.fn.months=d.fn.month;d.fn.weeks=d.fn.week;d.fn.isoWeeks=d.fn.isoWeek;d.fn.toJSON=
d.fn.toISOString;r(d.duration.fn=B.prototype,{_bubble:function(){var a=this._milliseconds,b=this._days,c=this._months,d=this._data;d.milliseconds=a%1E3;a=q(a/1E3);d.seconds=a%60;a=q(a/60);d.minutes=a%60;a=q(a/60);d.hours=a%24;b+=q(a/24);d.days=b%30;c+=q(b/30);d.months=c%12;b=q(c/12);d.years=b},weeks:function(){return q(this.days()/7)},valueOf:function(){return this._milliseconds+864E5*this._days+this._months%12*2592E6+31536E6*g(this._months/12)},humanize:function(a){var b=+this,c;c=!a;var d=this.lang(),
f=u(Math.abs(b)/1E3),h=u(f/60),g=u(h/60),k=u(g/24),l=u(k/365),f=45>f&&["s",f]||1===h&&["m"]||45>h&&["mm",h]||1===g&&["h"]||22>g&&["hh",g]||1===k&&["d"]||25>=k&&["dd",k]||45>=k&&["M"]||345>k&&["MM",u(k/30)]||1===l&&["y"]||["yy",l];f[2]=c;f[3]=0<b;f[4]=d;c=ra.apply({},f);a&&(c=this.lang().pastFuture(b,c));return this.lang().postformat(c)},add:function(a,b){var c=d.duration(a,b);this._milliseconds+=c._milliseconds;this._days+=c._days;this._months+=c._months;this._bubble();return this},subtract:function(a,
b){var c=d.duration(a,b);this._milliseconds-=c._milliseconds;this._days-=c._days;this._months-=c._months;this._bubble();return this},get:function(a){a=n(a);return this[a.toLowerCase()+"s"]()},as:function(a){a=n(a);return this["as"+a.charAt(0).toUpperCase()+a.slice(1)+"s"]()},lang:d.fn.lang});for(k in J)J.hasOwnProperty(k)&&(Y(k,J[k]),ua(k.toLowerCase()));Y("Weeks",6048E5);d.duration.fn.asMonths=function(){return(+this-31536E6*this.years())/2592E6+12*this.years()};d.lang("en",{ordinal:function(a){var b=
a%10,b=1===g(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th";return a+b}});O?(module.exports=d,H()):"function"===typeof define&&define.amd?define("moment",function(a,b,c){!0!==c.config().noGlobal&&H();return d}):H()}).call(this);
