<?xml version="1.0" encoding="utf-8"?><Database Name="db_dentista" Class="ContextoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=db_dentista;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="db_dentistaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Antecedentes" Member="Antecedentes">
    <Type Name="Antecedentes">
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_antecedente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioEmpleado" Member="UsuarioEmpleado">
    <Type Name="UsuarioEmpleado">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changepass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bitacora" Member="Bitacora">
    <Type Name="Bitacora">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaHora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cita" Member="Cita">
    <Type Name="Cita">
      <Column Name="idcita" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idempresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="libre" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="atendido" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente_Paciente" Member="Cliente_Paciente">
    <Type Name="Cliente_Paciente">
      <Column Name="id_usuariocliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsPrincipal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clinica" Member="Clinica">
    <Type Name="Clinica">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ImagenLogo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuarioCreacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaDeModificacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CantidadConsultorios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ComentariosClinica" Member="ComentariosClinica">
    <Type Name="ComentariosClinica">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuarioPaciente" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Componente" Member="Componente">
    <Type Name="Componente">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDFormulario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contador" Member="Contador">
    <Type Name="Contador">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hora" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Dia" Member="Dia">
    <Type Name="Dia">
      <Column Name="iddia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_corto" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Dosificacion" Member="Dosificacion">
    <Type Name="Dosificacion">
      <Column Name="fecha_registro" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nro_autorizacion" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="llave_dosificacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NextFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fecha_limite" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa_Cliente" Member="Empresa_Cliente">
    <Type Name="Empresa_Cliente">
      <Column Name="id_empresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_usuariocliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Envio" Member="Envio">
    <Type Name="Envio">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.factura_odontoweb" Member="factura_odontoweb">
    <Type Name="factura_odontoweb">
      <Column Name="Nit_dacasys" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nro_factura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nro_autorizacion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_emision" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="nombre_cliente" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="nit_cliente" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_control" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fecha_limite" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="detalle_cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precio_unitario" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Historico_Paciente" Member="Historico_Paciente">
    <Type Name="Historico_Paciente">
      <Column Name="id_empresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titulo_numero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estimacion_citas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="citas_realizadas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Historico_Paciente_det" Member="Historico_Paciente_det">
    <Type Name="Historico_Paciente_det">
      <Column Name="id_empresa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nro_detalle" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="trabajo_realizado" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="trabajo_a_realizar" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_cita" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Horario" Member="Horario">
    <Type Name="Horario">
      <Column Name="idhorario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="num_horario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="iddia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idempresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LogErrores" Member="LogErrores">
    <Type Name="LogErrores">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Modulo" Member="Modulo">
    <Type Name="Modulo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NotificacionConsultorio" Member="NotificacionConsultorio">
    <Type Name="NotificacionConsultorio">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TipoNotificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pago" Member="Pago">
    <Type Name="Pago">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCuentaPorCobrar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ParametroSistemas" Member="ParametroSistemas">
    <Type Name="ParametroSistemas">
      <Column Name="IDParametro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Elemento" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ValorS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Planilla_Vendedores" Member="Planilla_Vendedores">
    <Type Name="Planilla_Vendedores">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monto3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MontoTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Componente" Member="Rol_Componente">
    <Type Name="Rol_Componente">
      <Column Name="ID_Rol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Componente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Formulario" Member="Rol_Formulario">
    <Type Name="Rol_Formulario">
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDFormulario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rol_Modulo" Member="Rol_Modulo">
    <Type Name="Rol_Modulo">
      <Column Name="IDRol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDModulo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TefonosClinica" Member="TefonosClinica">
    <Type Name="TefonosClinica">
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTelefono" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Telefono" Member="Telefono">
    <Type Name="Telefono">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Member="Telefono1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TelefonoConsultorio" Member="TelefonoConsultorio">
    <Type Name="TelefonoConsultorio">
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTelefono" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tiempo_Consulta" Member="Tiempo_Consulta">
    <Type Name="Tiempo_Consulta">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TipoNotificacion" Member="TipoNotificacion">
    <Type Name="TipoNotificacion">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Trabajos" Member="Trabajos">
    <Type Name="Trabajos">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TrabajosConsultorio" Member="TrabajosConsultorio">
    <Type Name="TrabajosConsultorio">
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTrabajo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioCliente" Member="UsuarioCliente">
    <Type Name="UsuarioCliente">
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="changepass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Formulario" Member="Formulario">
    <Type Name="Formulario">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDModulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dacasys" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricoFichaDet" Member="HistoricoFichaDet">
    <Type Name="HistoricoFichaDet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDHistoricoFichaCab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pieza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrabajoRealizado" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricoFichaTrabajo" Member="HistoricoFichaTrabajo">
    <Type Name="HistoricoFichaTrabajo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDHistoricoFichaCab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pieza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Costo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CuentasPorCobrar" Member="CuentasPorCobrar">
    <Type Name="CuentasPorCobrar">
      <Column Name="Descripcion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDTrabajo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="IDConsultorio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDHistoricoFichaCab" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Paciente">
    <Type Name="Paciente">
      <Column Name="id_paciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ci" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nro_telefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipo_sangre" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="antecedente" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Licencia" Member="Licencia">
    <Type Name="Licencia">
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaFin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TipoLicencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NIT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaModificacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuarioCreador" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDIntervalo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricoPaciente" Member="HistoricoPaciente">
    <Type Name="HistoricoPaciente">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdHistoricoFichaCab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LugarNacimiento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Ocupacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GradoInstruccion" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EstadoCivil" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NacionesOriginarias" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Idioma" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PersonaInformacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApellidoPaternoPI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApellidoMaternoPI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombresPI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DireccionPI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoPI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AntPatFam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Anemia" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cardiopatias" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnfGastricas" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Hepatitis" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tuberculosis" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Asma" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiabetesMel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Epilepsia" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Hipertension" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VIH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OtrosAntP" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Alergias" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Embarazo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TratamientoMedico" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Medicamento" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="HemorragiaExtDent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GangliosLinf" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Respirador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OtrosExtOral" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Labios" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Lengua" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Paladar" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PisoBoca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MucosaYugal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Encias" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isProtesisDental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FecUltVisita" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="isFuma" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isBebe" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OtroHabitos" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isCepilloDental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isHiloDental" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isEnjuagueBucal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FrecCepDent" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isSangreEncias" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HigieneBucal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Sext17_16" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sext11" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sext26_27" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sext46_47" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sext31" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sext37_36" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cminuscula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="E" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ominuscula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalCEO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmayuscula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ei" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Omayuscula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalCPO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPiezasSanas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPiezasDent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoricoFichaCab" Member="HistoricoFichaCab">
    <Type Name="HistoricoFichaCab">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPaciente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdConsultorio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Odontograma" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ValoresOdontograma" Member="ValoresOdontograma">
    <Type Name="ValoresOdontograma">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="T" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="P" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Criterio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ValoresPeriodontal" Member="ValoresPeriodontal">
    <Type Name="ValoresPeriodontal">
      <Column Name="ID" Type="System.String" DbType="VarChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>