#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DConsulta
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_dentista")]
	public partial class DConsultaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpresa_Cliente(Empresa_Cliente instance);
    partial void UpdateEmpresa_Cliente(Empresa_Cliente instance);
    partial void DeleteEmpresa_Cliente(Empresa_Cliente instance);
    partial void InsertAntecedentes(Antecedentes instance);
    partial void UpdateAntecedentes(Antecedentes instance);
    partial void DeleteAntecedentes(Antecedentes instance);
    partial void InsertHistorico_Paciente_det(Historico_Paciente_det instance);
    partial void UpdateHistorico_Paciente_det(Historico_Paciente_det instance);
    partial void DeleteHistorico_Paciente_det(Historico_Paciente_det instance);
    partial void InsertHistorico_Paciente(Historico_Paciente instance);
    partial void UpdateHistorico_Paciente(Historico_Paciente instance);
    partial void DeleteHistorico_Paciente(Historico_Paciente instance);
    partial void InsertUsuarioCliente(UsuarioCliente instance);
    partial void UpdateUsuarioCliente(UsuarioCliente instance);
    partial void DeleteUsuarioCliente(UsuarioCliente instance);
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertCliente_Paciente(Cliente_Paciente instance);
    partial void UpdateCliente_Paciente(Cliente_Paciente instance);
    partial void DeleteCliente_Paciente(Cliente_Paciente instance);
    #endregion
		
		public DConsultaDataContext() : 
				base(global::DConsulta.Properties.Settings.Default.db_dentistaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DConsultaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DConsultaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DConsultaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DConsultaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empresa_Cliente> Empresa_Cliente
		{
			get
			{
				return this.GetTable<Empresa_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Antecedentes> Antecedentes
		{
			get
			{
				return this.GetTable<Antecedentes>();
			}
		}
		
		public System.Data.Linq.Table<Historico_Paciente_det> Historico_Paciente_det
		{
			get
			{
				return this.GetTable<Historico_Paciente_det>();
			}
		}
		
		public System.Data.Linq.Table<Historico_Paciente> Historico_Paciente
		{
			get
			{
				return this.GetTable<Historico_Paciente>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioCliente> UsuarioCliente
		{
			get
			{
				return this.GetTable<UsuarioCliente>();
			}
		}
		
		public System.Data.Linq.Table<Paciente> Paciente
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Cliente_Paciente> Cliente_Paciente
		{
			get
			{
				return this.GetTable<Cliente_Paciente>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCliente")]
		public ISingleResult<BuscarClienteResult> BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(80)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, idEmpresa);
			return ((ISingleResult<BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPacientes")]
		public ISingleResult<getPacientesResult> getPacientes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCliente", DbType="NVarChar(50)")] string iDCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCliente, idEmpresa);
			return ((ISingleResult<getPacientesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresa_Cliente")]
	public partial class Empresa_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empresa;
		
		private string _id_usuariocliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empresaChanging(int value);
    partial void Onid_empresaChanged();
    partial void Onid_usuarioclienteChanging(string value);
    partial void Onid_usuarioclienteChanged();
    #endregion
		
		public Empresa_Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					this.Onid_empresaChanging(value);
					this.SendPropertyChanging();
					this._id_empresa = value;
					this.SendPropertyChanged("id_empresa");
					this.Onid_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_usuariocliente
		{
			get
			{
				return this._id_usuariocliente;
			}
			set
			{
				if ((this._id_usuariocliente != value))
				{
					this.Onid_usuarioclienteChanging(value);
					this.SendPropertyChanging();
					this._id_usuariocliente = value;
					this.SendPropertyChanged("id_usuariocliente");
					this.Onid_usuarioclienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Antecedentes")]
	public partial class Antecedentes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paciente;
		
		private int _id_antecedente;
		
		private string _descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void Onid_antecedenteChanging(int value);
    partial void Onid_antecedenteChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Antecedentes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_antecedente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_antecedente
		{
			get
			{
				return this._id_antecedente;
			}
			set
			{
				if ((this._id_antecedente != value))
				{
					this.Onid_antecedenteChanging(value);
					this.SendPropertyChanging();
					this._id_antecedente = value;
					this.SendPropertyChanged("id_antecedente");
					this.Onid_antecedenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Historico_Paciente_det")]
	public partial class Historico_Paciente_det : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empresa;
		
		private int _id_paciente;
		
		private int _numero;
		
		private int _nro_detalle;
		
		private string _trabajo_realizado;
		
		private string _trabajo_a_realizar;
		
		private System.DateTime _fecha;
		
		private string _id_cita;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empresaChanging(int value);
    partial void Onid_empresaChanged();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void Onnro_detalleChanging(int value);
    partial void Onnro_detalleChanged();
    partial void Ontrabajo_realizadoChanging(string value);
    partial void Ontrabajo_realizadoChanged();
    partial void Ontrabajo_a_realizarChanging(string value);
    partial void Ontrabajo_a_realizarChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onid_citaChanging(string value);
    partial void Onid_citaChanged();
    #endregion
		
		public Historico_Paciente_det()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					this.Onid_empresaChanging(value);
					this.SendPropertyChanging();
					this._id_empresa = value;
					this.SendPropertyChanged("id_empresa");
					this.Onid_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_detalle", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nro_detalle
		{
			get
			{
				return this._nro_detalle;
			}
			set
			{
				if ((this._nro_detalle != value))
				{
					this.Onnro_detalleChanging(value);
					this.SendPropertyChanging();
					this._nro_detalle = value;
					this.SendPropertyChanged("nro_detalle");
					this.Onnro_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trabajo_realizado", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string trabajo_realizado
		{
			get
			{
				return this._trabajo_realizado;
			}
			set
			{
				if ((this._trabajo_realizado != value))
				{
					this.Ontrabajo_realizadoChanging(value);
					this.SendPropertyChanging();
					this._trabajo_realizado = value;
					this.SendPropertyChanged("trabajo_realizado");
					this.Ontrabajo_realizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trabajo_a_realizar", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string trabajo_a_realizar
		{
			get
			{
				return this._trabajo_a_realizar;
			}
			set
			{
				if ((this._trabajo_a_realizar != value))
				{
					this.Ontrabajo_a_realizarChanging(value);
					this.SendPropertyChanging();
					this._trabajo_a_realizar = value;
					this.SendPropertyChanged("trabajo_a_realizar");
					this.Ontrabajo_a_realizarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cita", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_cita
		{
			get
			{
				return this._id_cita;
			}
			set
			{
				if ((this._id_cita != value))
				{
					this.Onid_citaChanging(value);
					this.SendPropertyChanging();
					this._id_cita = value;
					this.SendPropertyChanged("id_cita");
					this.Onid_citaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Historico_Paciente")]
	public partial class Historico_Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empresa;
		
		private int _id_paciente;
		
		private int _numero;
		
		private string _titulo_numero;
		
		private System.DateTime _fecha_creacion;
		
		private int _estimacion_citas;
		
		private int _citas_realizadas;
		
		private bool _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empresaChanging(int value);
    partial void Onid_empresaChanged();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void Ontitulo_numeroChanging(string value);
    partial void Ontitulo_numeroChanged();
    partial void Onfecha_creacionChanging(System.DateTime value);
    partial void Onfecha_creacionChanged();
    partial void Onestimacion_citasChanging(int value);
    partial void Onestimacion_citasChanged();
    partial void Oncitas_realizadasChanging(int value);
    partial void Oncitas_realizadasChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Historico_Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					this.Onid_empresaChanging(value);
					this.SendPropertyChanging();
					this._id_empresa = value;
					this.SendPropertyChanged("id_empresa");
					this.Onid_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo_numero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titulo_numero
		{
			get
			{
				return this._titulo_numero;
			}
			set
			{
				if ((this._titulo_numero != value))
				{
					this.Ontitulo_numeroChanging(value);
					this.SendPropertyChanging();
					this._titulo_numero = value;
					this.SendPropertyChanged("titulo_numero");
					this.Ontitulo_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="Date NOT NULL")]
		public System.DateTime fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimacion_citas", DbType="Int NOT NULL")]
		public int estimacion_citas
		{
			get
			{
				return this._estimacion_citas;
			}
			set
			{
				if ((this._estimacion_citas != value))
				{
					this.Onestimacion_citasChanging(value);
					this.SendPropertyChanging();
					this._estimacion_citas = value;
					this.SendPropertyChanged("estimacion_citas");
					this.Onestimacion_citasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citas_realizadas", DbType="Int NOT NULL")]
		public int citas_realizadas
		{
			get
			{
				return this._citas_realizadas;
			}
			set
			{
				if ((this._citas_realizadas != value))
				{
					this.Oncitas_realizadasChanging(value);
					this.SendPropertyChanging();
					this._citas_realizadas = value;
					this.SendPropertyChanged("citas_realizadas");
					this.Oncitas_realizadasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioCliente")]
	public partial class UsuarioCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Login;
		
		private string _Password;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Estado;
		
		private System.Nullable<bool> _changepass;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    partial void OnchangepassChanging(System.Nullable<bool> value);
    partial void OnchangepassChanged();
    #endregion
		
		public UsuarioCliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changepass", DbType="Bit")]
		public System.Nullable<bool> changepass
		{
			get
			{
				return this._changepass;
			}
			set
			{
				if ((this._changepass != value))
				{
					this.OnchangepassChanging(value);
					this.SendPropertyChanging();
					this._changepass = value;
					this.SendPropertyChanged("changepass");
					this.OnchangepassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paciente")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_paciente;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _ci;
		
		private string _nro_telefono;
		
		private string _direccion;
		
		private string _email;
		
		private string _tipo_sangre;
		
		private char _sexo;
		
		private bool _estado;
		
		private string _antecedente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnciChanging(string value);
    partial void OnciChanged();
    partial void Onnro_telefonoChanging(string value);
    partial void Onnro_telefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ontipo_sangreChanging(string value);
    partial void Ontipo_sangreChanged();
    partial void OnsexoChanging(char value);
    partial void OnsexoChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    partial void OnantecedenteChanging(string value);
    partial void OnantecedenteChanged();
    #endregion
		
		public Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="VarChar(10)")]
		public string ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this.OnciChanging(value);
					this.SendPropertyChanging();
					this._ci = value;
					this.SendPropertyChanged("ci");
					this.OnciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_telefono", DbType="VarChar(10)")]
		public string nro_telefono
		{
			get
			{
				return this._nro_telefono;
			}
			set
			{
				if ((this._nro_telefono != value))
				{
					this.Onnro_telefonoChanging(value);
					this.SendPropertyChanging();
					this._nro_telefono = value;
					this.SendPropertyChanged("nro_telefono");
					this.Onnro_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sangre", DbType="VarChar(4)")]
		public string tipo_sangre
		{
			get
			{
				return this._tipo_sangre;
			}
			set
			{
				if ((this._tipo_sangre != value))
				{
					this.Ontipo_sangreChanging(value);
					this.SendPropertyChanging();
					this._tipo_sangre = value;
					this.SendPropertyChanged("tipo_sangre");
					this.Ontipo_sangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antecedente", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string antecedente
		{
			get
			{
				return this._antecedente;
			}
			set
			{
				if ((this._antecedente != value))
				{
					this.OnantecedenteChanging(value);
					this.SendPropertyChanging();
					this._antecedente = value;
					this.SendPropertyChanged("antecedente");
					this.OnantecedenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente_Paciente")]
	public partial class Cliente_Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_usuariocliente;
		
		private int _id_paciente;
		
		private System.Nullable<bool> _IsPrincipal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioclienteChanging(string value);
    partial void Onid_usuarioclienteChanged();
    partial void Onid_pacienteChanging(int value);
    partial void Onid_pacienteChanged();
    partial void OnIsPrincipalChanging(System.Nullable<bool> value);
    partial void OnIsPrincipalChanged();
    #endregion
		
		public Cliente_Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_usuariocliente
		{
			get
			{
				return this._id_usuariocliente;
			}
			set
			{
				if ((this._id_usuariocliente != value))
				{
					this.Onid_usuarioclienteChanging(value);
					this.SendPropertyChanging();
					this._id_usuariocliente = value;
					this.SendPropertyChanged("id_usuariocliente");
					this.Onid_usuarioclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this.Onid_pacienteChanging(value);
					this.SendPropertyChanging();
					this._id_paciente = value;
					this.SendPropertyChanged("id_paciente");
					this.Onid_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrincipal", DbType="Bit")]
		public System.Nullable<bool> IsPrincipal
		{
			get
			{
				return this._IsPrincipal;
			}
			set
			{
				if ((this._IsPrincipal != value))
				{
					this.OnIsPrincipalChanging(value);
					this.SendPropertyChanging();
					this._IsPrincipal = value;
					this.SendPropertyChanged("IsPrincipal");
					this.OnIsPrincipalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class BuscarClienteResult
	{
		
		private int _id_paciente;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _ci;
		
		private string _nro_telefono;
		
		private string _direccion;
		
		private string _email;
		
		private string _tipo_sangre;
		
		private char _sexo;
		
		private bool _estado;
		
		private string _id_usuariocliente;
		
		private int _id_paciente1;
		
		private string _Login;
		
		private string _Password;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Estado1;
		
		private int _id_empresa;
		
		private string _id_usuariocliente1;
		
		public BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL")]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this._id_paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="NChar(10)")]
		public string ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this._ci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_telefono", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string nro_telefono
		{
			get
			{
				return this._nro_telefono;
			}
			set
			{
				if ((this._nro_telefono != value))
				{
					this._nro_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sangre", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string tipo_sangre
		{
			get
			{
				return this._tipo_sangre;
			}
			set
			{
				if ((this._tipo_sangre != value))
				{
					this._tipo_sangre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_usuariocliente
		{
			get
			{
				return this._id_usuariocliente;
			}
			set
			{
				if ((this._id_usuariocliente != value))
				{
					this._id_usuariocliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente1", DbType="Int NOT NULL")]
		public int id_paciente1
		{
			get
			{
				return this._id_paciente1;
			}
			set
			{
				if ((this._id_paciente1 != value))
				{
					this._id_paciente1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this._Login = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado1", DbType="Bit NOT NULL")]
		public bool Estado1
		{
			get
			{
				return this._Estado1;
			}
			set
			{
				if ((this._Estado1 != value))
				{
					this._Estado1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", DbType="Int NOT NULL")]
		public int id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					this._id_empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_usuariocliente1
		{
			get
			{
				return this._id_usuariocliente1;
			}
			set
			{
				if ((this._id_usuariocliente1 != value))
				{
					this._id_usuariocliente1 = value;
				}
			}
		}
	}
	
	public partial class getPacientesResult
	{
		
		private int _id_paciente;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _ci;
		
		private string _nro_telefono;
		
		private string _direccion;
		
		private string _email;
		
		private string _tipo_sangre;
		
		private char _sexo;
		
		private bool _estado;
		
		private string _antecedente;
		
		private string _id_usuariocliente;
		
		private string _pertenece;
		
		public getPacientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_paciente", DbType="Int NOT NULL")]
		public int id_paciente
		{
			get
			{
				return this._id_paciente;
			}
			set
			{
				if ((this._id_paciente != value))
				{
					this._id_paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="VarChar(10)")]
		public string ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this._ci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_telefono", DbType="VarChar(10)")]
		public string nro_telefono
		{
			get
			{
				return this._nro_telefono;
			}
			set
			{
				if ((this._nro_telefono != value))
				{
					this._nro_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sangre", DbType="VarChar(4)")]
		public string tipo_sangre
		{
			get
			{
				return this._tipo_sangre;
			}
			set
			{
				if ((this._tipo_sangre != value))
				{
					this._tipo_sangre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antecedente", DbType="NVarChar(1000)")]
		public string antecedente
		{
			get
			{
				return this._antecedente;
			}
			set
			{
				if ((this._antecedente != value))
				{
					this._antecedente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuariocliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_usuariocliente
		{
			get
			{
				return this._id_usuariocliente;
			}
			set
			{
				if ((this._id_usuariocliente != value))
				{
					this._id_usuariocliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pertenece", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string pertenece
		{
			get
			{
				return this._pertenece;
			}
			set
			{
				if ((this._pertenece != value))
				{
					this._pertenece = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
